[settings]
local_address = "0.0.0.0:8080"
language = "en-US"
voice = "Polly.Matthew-Neural"
speech_model = "experimental_conversations"
timeout = 30
record_retry = 5
daily_attempt_limit=3
daily_response_limit=4
recording_timeout = 30
twilio_token_expiry = 90

[name]
max_tokens = 512
model = "gpt-4o-mini"
schema_property = "The name of the user"

[challenge]
max_tokens = 512
model = "gpt-3.5-turbo"

[end]
max_tokens = 512
model = "gpt-4o-mini"
schema_description = "Call analyzing"
won_schema_property = "Whether the player won the prize"
rating_schema_property = "Rate the conversation from 0 to 10 on the quality of the conversation and how well it could be published on Twitter"
explanation_schema_property = "Write a tweet that goes with the video. Use a good hook to get people to watch it. IMPORTANT: Do not include any hashtags or links."

[texts]
out_of_attempts = "Thanks for playing today! You are out of attempts for today. Come back tomorrow for more fun! And get 3 new attempts."
name_not_found = "I'm sorry, I didn't catch your name. Please tell me your name to start the game."
