[settings]
local_address = "0.0.0.0:8080"
language = "en-US"
voice = "Polly.Matthew-Neural"
speech_model = "experimental_conversations"
timeout = 30
record_retry = 5
daily_attempt_limit=0
daily_response_limit=1
recording_timeout = 30
twilio_token_expiry = 90

[name]
max_tokens = 512
model = "gpt-4o-mini"
schema_property = "The name of the user"

[challenge]
max_tokens = 512
model = "gpt-3.5-turbo"

[end]
max_tokens = 512
model = "gpt-4o-mini"
schema_description = "Call analyzing"
won_schema_property = "Whether the player won the prize"
rating_schema_property = "Rate the conversation from 0 to 10 on how well it could be published"
explanation_schema_property = "Explain why you rated the conversation as you did"

[texts]
out_of_attempts = "The second round of why dot fun was incredibly successful! It is closed now. Stay tuned for round 3, keep an eye out on our X account or the why dot fun website."
name_not_found = "I'm sorry, I didn't catch your name. Please tell me your name to start the game."
