[settings]
local_address = "0.0.0.0:8080"
language = "en-US"
voice = "Polly.Matthew-Neural"
speech_model = "experimental_conversations"
timeout = 30
record_retry = 5
daily_attempt_limit=3
daily_response_limit=5

[name]
max_tokens = 512
model = "gpt-4o-mini"
schema_property = "The name of the user"

[challenge]
max_tokens = 512
model = "gpt-3.5-turbo"

[end]
max_tokens = 512
model = "gpt-4o-mini"
schema_description = "Analyzes the previous conversation and determines if the player won the prize"
schema_property = "Whether the player won the prize"

[texts]
out_of_attempts = "You have reached the maximum number of $attempts attempts for today. Please try again tomorrow."
name_not_found = "I'm sorry, I didn't catch your name. Please tell me your name to start the game."